# Generated by Django 4.2.4 on 2023-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
